### ISSUE TITLE
Check proprietary status

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/cosmo#14]
Check the status of data- if it's proprietary set group to cosgo, else cosstis. From Deb Kenny:
The release date can be found in a couple of tables in the dadsops database:
sci_release_date in the science table
ads_release_date in the archive_data_set_all table
The time is in GMT.

**Comment by justincely** [comment]
for an [example:](https://github.com/justincely/lightcurve_pipeline/blob/master/lightcurve_pipeline/scripts/download_hstlc.py#L229)

**Comment by jotaylor** [comment]
Done and done.
