### ISSUE TITLE
Update travis hook to new repo name.

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/cosmo#15]
It's not running now because we changed the name from cos_monitoring to cosmo.

**Comment by jotaylor** [comment]
I think. I'm a travis n00b.

**Comment by justincely** [comment]
@jotaylor, looks like it's running: [status](https://travis-ci.org/spacetelescope/cosmo)  the last commit was from one of @mfixstsci branches, which run 25 days ago.  What makes you think it's not running?

**Comment by jotaylor** [comment]
Oops. This is a fail on my part. My badge in the README points to the old name. So, wrong name point, but it's on my end ;)
