### ISSUE TITLE
confirm retrieval in new structure works as expected

### ISSUE THREAD

**Issue by jwhite3** [spacetelescope/cosmo#50]
need to determine which changes need to be merged from the current "operating" branch, `cmagness` to pr #47

**Comment by jwhite3** [comment]
With all of the changes that we've made, I'm not sure that this is even valid anymore.. I'm closing this for now

**Comment by cmagness** [comment]
i don't need to merge that branch into master as much as i need to confirm that the retrieval version that is in the master branch runs properly for me (in the same way as the cmagness branch)

**Comment by cmagness** [comment]
reopening this to confirm retrieval works in new structure. related to `https://github.com/spacetelescope/cosmo/issues/52`

**Comment by cmagness** [comment]
reopening this to confirm retrieval works in new structure. related to #52

**Comment by jwhite3** [comment]
Also relates to #44

**Comment by jwhite3** [comment]
resolved by #139 

Development on retrieval will continue outside of this project
