### ISSUE TITLE
retrieval should get user information from one of the .yamls

### ISSUE THREAD

**Issue by cmagness** [spacetelescope/cosmo#52]
currently, in the [https://github.com/spacetelescope/cosmo/tree/cmagness](url) branch where i've made the retrieval process more user independent, it still requires changing the username in `retrieval_info.py`. this can easily be replaced by getting this information from either of the .yaml files necessary for the retrieval process.

**Comment by jwhite3** [comment]
relates to #47

**Comment by jwhite3** [comment]
cosmo runs on a "general" configuration file, so we should probably put it in there.

**Comment by jwhite3** [comment]
resolved by #139 

Development on retrieval will continue outside of this project
